# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:ios)

before_all do
  cocoapods(repo_update: true)
end

desc "Runs all the tests"
lane :test do
  scan(
    workspace:"MusicSearch.xcworkspace",
    scheme: "MusicSearch",
  )
  xcov(
    workspace: "MusicSearch.xcworkspace",
    scheme: "MusicSearch",
    minimum_coverage_percentage: 80.0,
    output_directory: "xcov_output"
  )
end
desc "Submit a new Beta Build to Apple TestFlight"
desc "This will also make sure the profile is up to date"
lane :beta do
  # match(type: "appstore") # more information: https://codesigning.guide
  gym # Build your app - more options available
  pilot

  # sh "your_script.sh"
  # You can also use other beta testing services here (run `fastlane actions`)
end

desc "Deploy a new version to the App Store"
lane :release do
  # match(type: "appstore")
  # snapshot
  gym # Build your app - more options available
  deliver(force: true)
  # frameit
end


